

const rankProduct = {
  "ALL": [
    {
      rank : 1,
      src : 'row6_all01.png',
      tit : '베이브 스킨 베이비 블루 쿠션',
      enTit : 'Babe Skin Baby Blue Cushion',
      price : 34000,
    },
    {
      rank : 2,
      src : 'row6_all02.png',
      tit : '버터 글로우 스틱 ',
      enTit : 'Butter Glow Stick',
      price : 16000,
    },
    {
      rank : 3,
      src : 'row6_all03.png',
      tit : '베리 샷 립 틴트',
      enTit : 'Berry Shot Lip Tint',
      price : 15300,
    },
    {
      rank : 4,
      src : 'row6_all04.png',
      tit : '오! 해피데이 립펜슬 ',
      enTit : 'Oh! Happy Day Lip Pencil',
      price : 14000,
    },
    {
      rank : 5,
      src : 'row6_all05.png',
      tit : '바이바이 마이 블레미시 컨실러',
      enTit : 'Bye Bye My Blemish Concealer',
      price : 15000,
    },
    {
      rank : 6,
      src : 'row6_all06.png',
      tit : '이지 글라이드 플랫 아이라이너 ',
      enTit : 'Easy Glide Flat Eyeliner ',
      price : 15000,
    },
    {
      rank : 7,
      src : 'row6_all07.png',
      tit : '프리티 이지 글리터 스틱',
      enTit : 'Pretty Easy Glitter Stick',
      price : 10050,
    },
    {
      rank : 8,
      src : 'row6_all08.png',
      tit : 'X2 더블 아이래쉬 컬러 ',
      enTit : 'X2 Double Eyelash Curler',
      price : 13000,
    },
  ],
  "FACE" : [
    {
      rank : 1,
      src : 'row6_face01.png',
      tit : '베이브 스킨 베이비 블루 쿠션',
      enTit : 'Babe Skin Baby Blue Cushion',
      price : 34000,
    },
    {
      rank : 2,
      src : 'row6_face02.png',
      tit : '돈 터치 글래스 핑크 쿠션 ',
      enTit : 'Dont Touch Glass Pink Cushion',
      price : 34000,
    },
    {
      rank : 3,
      src : 'row6_face03.png',
      tit : '새틴 웨어 헬시',
      enTit : 'Satin Wear Healthy',
      price : 34000,
    },
    {
      rank : 4,
      src : 'row6_face04.png',
      tit : '타즈마니안 페퍼 카밍 투피스 패드',
      enTit : 'Tazmanian Pepper Calming 2-Piece Pad',
      price : 28000,
    },
    {
      rank : 5,
      src : 'row6_face05.png',
      tit : '버터 글로우 스틱',
      enTit : 'Butter Glow Stick',
      price : 19000,
    },
    {
      rank : 6,
      src : 'row6_face06.png',
      tit : '바이바이 마이 블레미시 컨실러',
      enTit : 'Bye Bye My Blemish Concealer',
      price : 15000,
    },
  ],
  "EYE" : 
    [
      {
        rank : 1,
        src : 'row6_eye01.png',
        tit : '겟 루스 글리터 젤 ',
        enTit : 'Get Loose Glitter Gel',
        price : 14000,
      },
      {
        rank : 2,
        src : 'row6_eye02.png',
        tit : '글리터피디아 아이 팔레트 ',
        enTit : 'Glitterpedia Eye Palette',
        price : 28900,
      },
      {
        rank : 3,
        src : 'row6_eye03.png',
        tit : '프리티 이지 글리터 스틱  ',
        enTit : 'Pretty Easy Glitter Stick',
        price : 10500,
      },
      {
        rank : 4,
        src : 'row6_eye04.png',
        tit : '이지 글라이드 플랫 아이라이너 ',
        enTit : 'Easy Glide Flat Eyeliner ',
        price : 15000,
      },
      {
        rank : 5,
        src : 'row6_eye05.png',
        tit : '셰이퍼 디파이닝 아이브로우 펜슬 &픽서 set ',
        enTit : 'Shaper Defining Eyebrow Pencil  Fixer Set',
        price : 48450,
      },
      {
        rank : 6,
        src : 'row6_eye06.png',
        tit : '셰이퍼 디파이닝 아이브로우 펜슬',
        enTit : 'Shaper Defining Eyebrow Pencil ',
        price : 10640,
      },
      {
        rank : 7,
        src : 'row6_eye07.png',
        tit : '무드 샤워 페이스 팔레트 ',
        enTit : 'Mood Shower Face Palette',
        price : 26000,
      },
      {
        rank : 8,
        src : 'row6_eye08.png',
        tit : '탭 미 팔레트 듀오  ',
        enTit : 'Tap Me Palette Duo',
        price : 18000,
      },
    ],
    "LIP": [
      {
        rank : 1,
        src : 'row6_lip01.png',
        tit : '베리 샷 립 틴트',
        enTit : 'Berry Shot Lip Tint',
        price : 17000,
      },
      {
        rank : 2,
        src : 'row6_lip02.png',
        tit : '팝콘 시럽 립플럼퍼 ',
        enTit : 'Popcorn Syrup Lip Plumpe',
        price : 16000,
      },
      {
        rank : 3,
        src : 'row6_lip03.png',
        tit : '러브 허그 벨벳 틴트',
        enTit : 'Luv Hug Velvet Tint',
        price : 14000,
      },
      {
        rank : 4,
        src : 'row6_lip04.png',
        tit : '논-스티키 대즐 틴트',
        enTit : 'Non-Sticky Dazzle Tint',
        price : 14000,
      },
      {
        rank : 5,
        src : 'row6_lip05.png',
        tit : '글레시어 비건 립밤',
        enTit : 'Glacier Vegan Lip Balm',
        price : 15000,
      },
      {
        rank : 6,
        src : 'row6_lip06.png',
        tit : '레드 페퍼 페이스트 립밤',
        enTit : 'Red Pepper Paste Lip Balm',
        price : 14000,
      },
      {
        rank : 7,
        src : 'row6_lip07.png',
        tit : 'CJ 해찬들 콜라보 고추장 립밤',
        enTit : 'Red Pepper Paste Lip Balm',
        price : 14000,
      },
    ],
  "TOOL" : [
    {
      rank : 1,
      src : 'row6_tool01.png',
      tit : '데일리 립 브러쉬 ',
      enTit : 'Daily Lip Brush',
      price : 9000,
    },
    {
      rank : 2,
      src : 'row6_tool02.png',
      tit : 'X2 더블 아이래쉬 컬러',
      enTit : 'X2 Double Eyelash Curler',
      price : 13000,
    },
    {
      rank : 3,
      src : 'row6_tool03.png',
      tit : '토이 카메라+스티커',
      enTit : 'Toy Film Camera+Sticker',
      price : 12000,
    },
  ],
}